apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
        app.kubernetes.io/component: observability
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: collector
          image: otel/opentelemetry-collector-contrib:0.103.0@sha256:a3b1bd5db3a90e51e1f0d5f7be73f80fed46f29d3c220dc4a3a8e2c4cad3a4c5
          imagePullPolicy: IfNotPresent
          args: ["--config=/etc/otel/collector-config.yml"]
          env:
            - name: DEPLOYMENT_ENV
              value: dev
          ports:
            - name: otlp-grpc
              containerPort: 4317
            - name: prom
              containerPort: 8889
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: config
              mountPath: /etc/otel
              readOnly: true
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
        - name: tmp
          emptyDir:
            sizeLimit: 16Mi
